language: csharp
sudo: required
dist: trusty
env:
  - MONO_THREADS_PER_CPU=2000
mono:
  - 4.0.5
os:
  - linux
osx_image: xcode7.1
branches:
  only:
    - main
script:
  - ./build.sh
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi