<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), 'README.md'))\build\common.props" />
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <Description>NupkgWrench is a cross platform command line tool to read and modify nupkgs.</Description>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>nupkgwrench</ToolCommandName>
    <RollForward>Major</RollForward>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- Single file NupkgWrench.exe, see build.ps1 -->
  <PropertyGroup Condition="'$(PublishSingleFile)' == 'true'">
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <!-- NupkgWrenchExe package, see build.ps1 -->
  <PropertyGroup Condition="'$(PackageId)' == 'NupkgWrenchExe'">
    <PackAsTool>false</PackAsTool>
    <NuspecFile>NupkgWrenchExe.nuspec</NuspecFile>
    <NuspecProperties>version=$(Version);copyright=$(Copyright);branch=$(RepositoryBranch);commit=$(RepositoryCommit)</NuspecProperties>
  </PropertyGroup>

  <ItemGroup>
    <None Include="PACKAGE.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    <PackageReference Include="NuGet.Packaging" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
